// Turns the pulled namespaces into a TypeScript declaration file:
//
//   Layer 1 — `Resources` mirrors the key tree (string leaves) and augments
//             i18next's CustomTypeOptions, so t('ns:key') is autocompleted and
//             unknown keys are compile errors. (What i18next-resources-for-ts does.)
//
//   Layer 2 — `TranslationParams` maps every fully-qualified key to the object of
//             interpolation params it requires, parsed from the placeholder
//             dialects. Consumers wrap i18next's t with createTypedT to get
//             param typing i18next cannot infer from string values.
import { extractParams } from "./placeholders.js";
import { pluralBase } from "./plurals.js";
import type { Namespaces, TranslationTree } from "./types.js";

export interface EmitOptions {
  // Emit Layer 2 (TranslationParams). On by default.
  params?: boolean;
  // Source locale, recorded in the file header for provenance.
  locale?: string;
}

const HEADER = (locale?: string) =>
  `// Generated by @language-bridge/cli — do not edit.\n` +
  `// Source locale: ${locale ?? "unknown"}. Re-run \`lb sync\` to update.\n` +
  `/* eslint-disable */\n`;

function quote(key: string): string {
  return JSON.stringify(key);
}

// Recursively render a tree as a TypeScript object type with `string` leaves.
function renderTree(tree: TranslationTree, indent: string): string {
  const inner = indent + "  ";
  const lines = Object.keys(tree)
    .sort()
    .map((key) => {
      const value = tree[key]!;
      const type = typeof value === "string" ? "string" : renderTree(value, inner);
      return `${inner}${quote(key)}: ${type};`;
    });
  return `{\n${lines.join("\n")}\n${indent}}`;
}

function renderResources(namespaces: Namespaces): string {
  const lines = Object.keys(namespaces)
    .sort()
    .map((ns) => `  ${quote(ns)}: ${renderTree(namespaces[ns]!, "  ")};`);
  return `export interface Resources {\n${lines.join("\n")}\n}`;
}

// Walk one namespace tree, yielding [dottedKeyPath, value] for each string leaf.
function* leaves(tree: TranslationTree, path: string[] = []): Generator<[string[], string]> {
  for (const key of Object.keys(tree)) {
    const value = tree[key]!;
    if (typeof value === "string") yield [[...path, key], value];
    else yield* leaves(value, [...path, key]);
  }
}

// fullKey ("ns:a.b") -> set of required param names, plural variants collapsed.
export function collectParams(namespaces: Namespaces): Map<string, Set<string>> {
  const params = new Map<string, Set<string>>();
  const plurals = new Set<string>();

  for (const ns of Object.keys(namespaces)) {
    for (const [segments, value] of leaves(namespaces[ns]!)) {
      const last = segments[segments.length - 1]!;
      const base = pluralBase(last);
      const keyPath = base === null ? segments : [...segments.slice(0, -1), base];
      const fullKey = `${ns}:${keyPath.join(".")}`;

      const set = params.get(fullKey) ?? new Set<string>();
      for (const name of extractParams(value)) set.add(name);
      if (base !== null) plurals.add(fullKey);
      params.set(fullKey, set);
    }
  }

  // `count` is implied by pluralisation, not the placeholder text.
  for (const key of plurals) params.get(key)!.add("count");
  return params;
}

function renderParams(namespaces: Namespaces): string {
  const params = collectParams(namespaces);
  const lines = [...params.keys()].sort().map((fullKey) => {
    const names = params.get(fullKey)!;
    // `{}` (not Record<string, never>) so `keyof` is `never` — that's how the
    // runtime helper detects a key that takes no params and drops the argument.
    if (names.size === 0) return `  ${quote(fullKey)}: {};`;
    const fields = [...names]
      .sort()
      .map((name) => `${quote(name)}: ${name === "count" ? "number" : "string | number"}`)
      .join("; ");
    return `  ${quote(fullKey)}: { ${fields} };`;
  });
  // A `type` (not `interface`) so it carries an implicit index signature and
  // satisfies the `ParamsMap` constraint on createTypedT.
  return `export type TranslationParams = {\n${lines.join("\n")}\n};`;
}

function renderAugmentation(namespaces: Namespaces): string {
  const defaultNs = Object.keys(namespaces).sort()[0];
  const defaultNsLine = defaultNs ? `    defaultNS: ${quote(defaultNs)};\n` : "";
  return (
    `declare module "i18next" {\n` +
    `  interface CustomTypeOptions {\n` +
    defaultNsLine +
    `    resources: Resources;\n` +
    `  }\n` +
    `}`
  );
}

// Full .d.ts contents for the given namespaces.
export function emit(namespaces: Namespaces, options: EmitOptions = {}): string {
  const wantParams = options.params ?? true;
  const blocks = [HEADER(options.locale), renderResources(namespaces)];
  if (wantParams) blocks.push(renderParams(namespaces));
  blocks.push(renderAugmentation(namespaces));
  return blocks.join("\n\n") + "\n";
}
