// Static shell-completion scripts generated from the live command list, so they
// never drift. Usage: `lb completion zsh > ...` (see help output per shell).
export interface CompletionCommand {
  name: string;
  description: string;
}

export const SHELLS = ["bash", "zsh"] as const;
export type Shell = (typeof SHELLS)[number];

export function completionScript(shell: Shell, commands: CompletionCommand[]): string {
  return shell === "bash" ? bash(commands) : zsh(commands);
}

function bash(commands: CompletionCommand[]): string {
  const words = commands.map((command) => command.name).join(" ");
  return `# lb bash completion — generated by \`lb completion bash\`.
# Install: lb completion bash >> ~/.bashrc  (or into bash_completion.d)
_lb_completions() {
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=($(compgen -W "${words}" -- "\${COMP_WORDS[1]}"))
  fi
}
complete -F _lb_completions lb
`;
}

function zsh(commands: CompletionCommand[]): string {
  const entries = commands
    .map((command) => `    '${command.name}:${command.description.replace(/'/g, "'\\''")}'`)
    .join("\n");
  return `#compdef lb
# lb zsh completion — generated by \`lb completion zsh\`.
# Install: lb completion zsh > "\${fpath[1]}/_lb" && compinit
_lb() {
  local -a commands
  commands=(
${entries}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' commands
  fi
}
_lb "$@"
`;
}
