// Codegen: render CLI-owned example snippets so the docs never drift from the
// CLI. Runs before `dev`/`build` (see package.json). Imports the single source of
// truth from the cli package and writes a generated module the MDX imports.
//
// Run manually: bun run scripts/gen-cli-snippets.ts
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { buildInstructions } from '../../cli/src/lib/instructions-template.ts';

const aiInstructionsExample = buildInstructions({
  project: 'my-app',
  source: 'en',
  locales: ['en', 'pt-BR', 'es'],
  namespaces: ['checkout', 'common'],
});

// Latest app version from the repo's release-please manifest ("." = server/app).
const manifest = JSON.parse(
  await readFile(join(import.meta.dir, '..', '..', '.release-please-manifest.json'), 'utf8'),
) as Record<string, string>;
const latestVersion = manifest['.'] ?? '0.0.0';

const outFile = join(import.meta.dir, '..', 'lib', 'generated', 'cli-snippets.ts');
await mkdir(dirname(outFile), { recursive: true });
await writeFile(
  outFile,
  `// AUTO-GENERATED by scripts/gen-cli-snippets.ts — do not edit.\n` +
    `// Source of truth: cli/src/lib/instructions-template.ts + .release-please-manifest.json\n` +
    `export const aiInstructionsExample = ${JSON.stringify(aiInstructionsExample)};\n` +
    `export const latestVersion = ${JSON.stringify(latestVersion)};\n`,
);

console.log(`Generated ${outFile}`);
